/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package org.dadosdeclima.view;

import org.dadosdeclima.model.DadoClimatico;
import org.dadosdeclima.observable.Observer;
import org.dadosdeclima.presenter.DadosPresenter;
import org.dadosdeclima.view.DadosTempo;

public class MainTela extends javax.swing.JFrame implements Observer
{
    private DadosPresenter presenter;
    private DadosTempo dadosTempoPanel;
    private Registros registrosPanel;
    private TelaDadosMedios dadosMediosPanel;
    private TelaLog logPanel;
    private UltimaAtt ultimaAttPanel;
    private TelaMinMax telaMinMax;
    
    /**
     * Creates new form MainTela
     */
    
    
    public MainTela(DadosPresenter presenter) {
        initComponents();
        this.presenter = presenter;
        dadosTempoPanel = new DadosTempo(presenter);
        dadosMediosPanel = new TelaDadosMedios(presenter);
        registrosPanel = new Registros(presenter);
        logPanel = new TelaLog();
        ultimaAttPanel = new UltimaAtt(presenter);
        telaMinMax = new TelaMinMax(presenter);

        jLabel1.setText("Numero de registros: " + presenter.getNumeroRegistros());

        addComponentsToMainPane();
        setVisible(true);
    }
    
    public final void addComponentsToMainPane()
    {
        desktopPane.add(dadosMediosPanel);
        desktopPane.add(registrosPanel);
        desktopPane.add(dadosTempoPanel);
        desktopPane.add(logPanel);
        desktopPane.add(ultimaAttPanel);
        desktopPane.add(telaMinMax);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openTelaLog = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dados de Clima");

        desktopPane.setRequestFocusEnabled(false);

        jLabel1.setText("Número de registros: xx");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Configuração");

        openTelaLog.setMnemonic('o');
        openTelaLog.setText("Log");
        openTelaLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openTelaLogActionPerformed(evt);
            }
        });
        fileMenu.add(openTelaLog);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(desktopPane)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 319, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openTelaLogActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_openTelaLogActionPerformed
        logPanel.setVisible(true);
    }//GEN-LAST:event_openTelaLogActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openTelaLog;

    @Override
    public void update(DadoClimatico event)
    {
        dadosMediosPanel.update(event);
        registrosPanel.update(event);
        ultimaAttPanel.update(event);
        telaMinMax.update(event);

        jLabel1.setText("Numero de registros: " + presenter.getNumeroRegistros());
    }
    // End of variables declaration//GEN-END:variables


    public TelaLog getLogPanel()
    {
        return logPanel;
    }
}
