/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.dadosdeclima.view;

import org.dadosdeclima.log.JsonLogger;
import org.dadosdeclima.log.LogAdapter;
import org.dadosdeclima.log.Logger;
import org.dadosdeclima.log.XmlLogger;
import org.dadosdeclima.model.DadoClimatico;
import org.dadosdeclima.observable.Observer;
import org.dadosdeclima.presenter.DadosPresenter;

import java.nio.file.Paths;

/**
 *
 * @author Ruan Ribeiro
 */
public class TelaLog extends javax.swing.JInternalFrame
{
    boolean jsonSelected;
    LogAdapter logger;
    String jsonFilePath;
    String xmlFilePath;
    /**
     * Creates new form TelaLog
     */
    public TelaLog() {
        jsonSelected = true;

        String dadosPath = Paths.get("").toAbsolutePath().toString();
        jsonFilePath = dadosPath + "\\dados\\log.json";
        xmlFilePath = dadosPath + "\\dados\\log.xml";

        logger = new LogAdapter(new JsonLogger(jsonFilePath));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        saveButtonLog = new javax.swing.JButton();
        labelLog = new javax.swing.JLabel();
        BOX = new javax.swing.JComboBox<>();

        setTitle("Configuração do Sistema");

        saveButtonLog.setText("Salvar");
        saveButtonLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonLogActionPerformed(evt);
            }
        });

        labelLog.setText("Log");

        BOX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JSON", "XML" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(saveButtonLog)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelLog)
                        .addGap(30, 30, 30)
                        .addComponent(BOX, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLog)
                    .addComponent(BOX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(saveButtonLog)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonLogActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_saveButtonLogActionPerformed
        jsonSelected = BOX.getSelectedIndex() == 0;

        if(jsonSelected)
        {
            logger.setLogger(new JsonLogger(jsonFilePath));
        }
        else
        {
            logger.setLogger(new XmlLogger(xmlFilePath));
        }
    }//GEN-LAST:event_saveButtonLogActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BOX;
    private javax.swing.JLabel labelLog;
    private javax.swing.JButton saveButtonLog;


    public void logRemocao()
    {
        logger.log("Remoção");
    }

    public void logInclusao()
    {
        logger.log("Inclusão");
    }
    // End of variables declaration//GEN-END:variables
}
