/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.dadosdeclima.view;

/**
 *
 * @author Ruan Ribeiro
 */
public class TelaDadosMedios extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaDadosMedios
     */
    public TelaDadosMedios() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        medTemperatura = new javax.swing.JLabel();
        medUmidade = new javax.swing.JLabel();
        medPressao = new javax.swing.JLabel();
        medNumReg = new javax.swing.JLabel();
        medFieldTemperatura = new javax.swing.JTextField();
        medFieldUmidade = new javax.swing.JTextField();
        medFieldPressao = new javax.swing.JTextField();
        medFieldNumReg = new javax.swing.JTextField();

        setTitle("Dados Médios");

        medTemperatura.setText("Temperatura");

        medUmidade.setText("Umidade");

        medPressao.setText("Pressão");

        medNumReg.setText("Número de Registros");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(medTemperatura)
                    .addComponent(medNumReg)
                    .addComponent(medPressao)
                    .addComponent(medUmidade))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(medFieldTemperatura, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(medFieldUmidade)
                    .addComponent(medFieldPressao)
                    .addComponent(medFieldNumReg))
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medTemperatura)
                    .addComponent(medFieldTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medFieldUmidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(medUmidade))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medFieldPressao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(medPressao))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medFieldNumReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(medNumReg))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField medFieldNumReg;
    private javax.swing.JTextField medFieldPressao;
    private javax.swing.JTextField medFieldTemperatura;
    private javax.swing.JTextField medFieldUmidade;
    private javax.swing.JLabel medNumReg;
    private javax.swing.JLabel medPressao;
    private javax.swing.JLabel medTemperatura;
    private javax.swing.JLabel medUmidade;
    // End of variables declaration//GEN-END:variables
}
